name: Build image and deploy to ECS
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_IMAGE_NAME: ecs-demo-node
  REACT_IMAGE_NAME: ecs-demo-client

jobs:
  build-image-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{vars.DOCKER_USERNAME}}/${{env.NODE_IMAGE_NAME}}
          tags: |
            latest
            v1.0.${{github.run_number}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./API-jokes
          file: ./API-jokes/Dockerfile.prod
          push: true
          tags: ${{steps.meta.outputs.tags}}
  build-image-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Added details to image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{vars.DOCKER_USERNAME}}/${{env.REACT_IMAGE_NAME}}
          tags: |
            latest
            v1.0.${{github.run_number}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./react-client
          file: ./react-client/Dockerfile.prod
          push: true
          build-args: |
            VITE_API_BASE_URL=http://ecsdemolb-1486322725.us-east-1.elb.amazonaws.com
          tags: ${{steps.meta.outputs.tags}}
